services:
  db:
    image: postgres
    volumes:
      - ./scripts/database:/docker-entrypoint-initdb.d/
    working_dir: /docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - csvgeneratornet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: report-generator
    volumes:
      - ./data:/reports
    environment:
      - CSV_DBHOST=db
      - CSV_DBPASS=root
      - CSV_SCHEDULE=${CSV_SCHEDULE:-@every 5s}
    depends_on:
      db:
        condition: service_healthy

    networks:
      - csvgeneratornet

networks:
  csvgeneratornet: